### PR TITLE
docs(deb): add `nmtui` and `nmcli`

### PR DESCRIPTION
**Pull request by initdc**
add `nmtui` for connnecting Wi-Fi for debian-like distro

you can connneting Wi-Fi with `nmtui` dialog,
 or `nmcli d wifi connect MyWi-Fi password MyPass`

ref: https://linuxhint.com/3-ways-to-connect-to-wifi-from-the-command-line-on-debian/

### CODE REVIEW

**Comment by htot** [comment]
Hi, did you note that this is the documentation for creating an Ubuntu image? For debian you can do `make debian`. Would you want to amend [that script](https://github.com/edison-fw/meta-intel-edison/blob/c6036298dfc81a1bb12190da49d7589e5ceec521/utils/debian_1_create.sh#L22) as well?

**Comment by initdc** [comment]
how about this script with `DEBIAN_FRONTEND="noninteractive"` and `set -e` https://github.com/initdc/rootfs-tools/blob/edison/buster/vendor-resources/intel-edison/root/config.sh

**Comment by htot** [comment]
Yes, and more improvements could be done too, see https://edison-fw.github.io/meta-intel-edison/2.6-Building-Debian.html. Feel free to send a patch :-)

For this patch, I see you add packages and remove packages. Is the net effect just adding nmtui and nmcli? Could you add a brief explanation to the commit message? Then I'll apply to https://github.com/htot/meta-intel-edison/tree/honister which will eventually be merged here.

**Comment by initdc** [comment]
https://github.com/initdc/debian-rootfs-tools/blob/master/deboot.rb#L16

**Comment by initdc** [comment]
Could you upload the `.deb` packages please?
```
sudo chroot $ROOTDIR /bin/bash -c "dpkg -i /tmp/deb/edison/kernel-*.deb"
sudo chroot $ROOTDIR /bin/bash -c "dpkg -r kernel-dev"
sudo chroot $ROOTDIR /bin/bash -c "dpkg -i /tmp/deb/all/bcm43340-fw_*.deb"
sudo chroot $ROOTDIR /bin/bash -c "dpkg -i /tmp/deb/corei7-64/gadget_*.deb"
```
It will be helpful for porting others linux distro for edison.

**Comment by htot** [comment]
64b version?

**Comment by initdc** [comment]
> 64b version?

Yes, I've build 32-bit version by using default conf.

**Comment by htot** [comment]
For now I push this to https://github.com/htot/meta-intel-edison/tree/honister this will eventually appear on edison-fw/master.

Thanks for the PR.

**Pull request closed without merging**
