### PR TITLE
Create Install_UbuntuBase_on_Edison.md

### PR DESCRIPTION
**Pull request by macvenez**
I hope it is well written in case just let me know for any edit to be made

### CODE REVIEW

**Comment by htot** [comment]
I'd like to merge into https://github.com/htot/meta-intel-edison first, then it will appear on https://htot.github.io/meta-intel-edison/ first.

To do that put the file under meta-intel-edison/docs/_docs/Edison/Building/ and add to the menu in meta-intel-edison/docs/_data/edison.yml

You can test that by (in your master branch) doing this yourself and configure github to create a site from your master branch /docs directory. It will then generate the site for you (after some minutes).

**Comment by macvenez** [comment]
Thanks, for all.
I tried it again, is it how it should be done now?
Never used Github apart from the main functions so I'm understanding maybe 2% of what I'm doing

**Comment by htot** [comment]
Seems ok, will try tomorrow. If you want to try, in the Settings for your repo, under Pages, you can select branch (patch-1) and directory (/docs) and after a minute or so it will have created the web site.

**Comment by htot** [comment]
These will go in through the Hardknott PR #142. Closing this, thanks!

**Pull request closed without merging**
