### PR TITLE
initramfs: check python packages prior to remove

### LINKED ISSUE #51: When acpi is not set clobber fails because python not found
https://github.com/edison-fw/meta-intel-edison/blob/a41f2a7d93e1e595ab682447639e94406cfe97a0/meta-intel-edison-distro/recipes-core/images/core-image-minimal-initramfs.bbappend#L22

Look like this needs to be either conditional on acpi or on the presence of the directory

### PR DESCRIPTION
**Pull request by htot**
This fixes #51

### CODE REVIEW

**Comment by alext-mkrs** [comment]
So I think we don't really need that logic in place - `rm -rf` should do the trick. Sorry for accidentally misleading you in #51 - I haven't noticed the `-f` didn't actually make it into my comment.

**Comment by htot** [comment]
Yeah, no problem. I think I already created this patch before I read your comment - and then was to lazy to change it. Mostly because I was wondering if -f removes the error condition, I thought it meant 'force'. But I 
see now and will change this, simple enough.

**Comment by htot** [comment]
This build without errors and the size of the compressed cpio is 3.2MB same as with my V1. Thanks for the suggestion.

**Comment by htot** [comment]
Merge it?

**Comment by alext-mkrs** [comment]
Yep

**Comment by htot** [comment]
merged, thanks

**Pull request merged**
