### PR TITLE
4.2-networking.md - passphrase

### PR DESCRIPTION
**Pull request by mwallnoefer**

### CODE REVIEW

**Comment by mwallnoefer** [comment]
Please don't forget this one

**Comment by htot** [comment]
Actually, [post-install ](https://github.com/edison-fw/meta-intel-edison/blob/6bc6d5f9de0599f5c26f86406f19b423a6fe0a69/meta-intel-edison-distro/recipes-core/post-install/files/post-install.sh#L37) sets the passphrase.

So why the minimum of 8?

**Comment by mwallnoefer** [comment]
It needs to be at least 8 chars long for the WPA2 standard?

**Comment by htot** [comment]
Is that a requirement from the standard (I didn't know) or from certain access points. I see that hostapd has a minimum of 8. Can't find a reference in the connman sources.

**Comment by mwallnoefer** [comment]
I think that it is required by the standard, also `configure_edison` had it hard-coded. And I have already tried with a shorter password where I ended up in an error.

**Comment by htot** [comment]
Alright. Did I read correct you dropped support wps and open networks?

**Comment by mwallnoefer** [comment]
Yes, since connman's tethering supports only WPA2?

**Comment by htot** [comment]
merged into https://github.com/htot/meta-intel-edison

**Pull request closed without merging**
